### ISSUE TITLE
部署失败 tars-server报错找不到类

### ISSUE THREAD

**Issue by ialak** [TarsPHP/tars-server#3]
https://github.com/TarsPHP/tars-server/blob/4a120f111746c0e8fdab08627541ad72372bdbf5/src/cmd/Start.php#L12
![图片](https://user-images.githubusercontent.com/3145698/54661708-41fd6500-4b16-11e9-9c17-78f05ce6a786.png)

**Comment by copyrenzhe** [comment]
已修复，请使用 tars-server 0.2.4及以上版本
